language: node_js
node_js:
- lts/*
before_script: npm run build
after_success: npm run coverage
deploy:
  skip_cleanup: true
  provider: npm
  email: npm@warerebel.com
  api_key:
    secure: oKLrV/qcc5Pq0Sr1DNFw6rpqujGlKKHf9c9SDwzhLguUsBTHKysqHWfdqmhW0K9EM59Re5wNCgpeBx9Ie7nYi1LsS821e4B6iRIVF+/7Ap1gKejZP/DZvZwlMT8/6Ql4EGX/SDnbUUkl1cPg4iGkE8SV2cP50yHS7qL9v/UvuSdLciViwoNut34mTMnZmyqybU1ILvPcbHDMeJr//P48XjBRAZyTpw6Jv8YAAlxsGR+vmlYPcMoQghJSfpP8VCiDYQXCt0Y++345odliNmCIw1hzV68M9SbHHWH/se9WDy4tYO1ME+xRKT3tsCrXM+14CLQDRcQ2saU/jB23x3lxEfSfdws2JXbHdo436fv5WgTrtHgBzTyGPoff6IY+HqaFG6eDBPxSBpmEFuKSOwO1pdlRjwFrWhMqyU9GBndd4tl2Hfim0YEoiKunEeK2myi/NBY6EhmWEfT/hyxsXj55GceU6HVvq0oSxCeE5TozKmcqQMsCUIzvOhNg6aIaBxjZGPhWPIYetagmCtSiwOq9/nYHUo7PX6sZbk6mg/xQfpyj6Ymg0KBrxupjlSM5BYrcGEabdW+DgXZRV+2z785FXQatX8non4sKUEDdWFsa+agdRhcMOndlx4XFqdGz1gQF3nDdD1Dpw19bgM55tfSd3g+GTd9RxkUhYT2zuvMqJgE=
  on:
    tags: true
    repo: warerebel/azureblobstoragehelper
