language: node_js
node_js:
- lts/*
before_script: npm run build
after_success: npm run coverage
deploy:
  skip_cleanup: true
  provider: npm
  repo: warerebel/azureblobstoragehelper
  email: npm@warerebel.com
  api_key:
    secure: "nztdda5oyyZkmvEM0cqLqfzGft3J9Y1HVtOiYT5ZPVwwU8BGBPzAmZBwKrMdjI8Dza3KAlv+AbvAQj5cScexUwuhRpnWFSl6KFeFNIzJHmcKUtAsvJxsTrEWePib6tfKCh2uYzPcI/Ecv2Ja7It/rmPtqV0W9N+jRrN+sCBriLanP9TXMP8KFIRXKu96Tr/IRplrgANWXCGVhYi2R0ufnjQh+Szgyqht7YohHvkUqEZJHcxhuYu/Sgnn1zIOMBCyVKT2t8BtI7qmxZ0pAtlVdUhUwMIMbirrRE0yT5mYarDe+/mO4kQIl4qmOqf7quZXtlviTjbyM2gssu34E0Njeo9mO8IgHXdaFKCEQt/e0EIYOTTMfmhEyQn3ewuIBeQ6CTXYJeiI3A9F3qwlkpiODdrcbMKZv2F+4LZwBm1ilyOu5N1hIXMDUgcGqh17IwOESM0JH4f3cb18FkXf/naOcNbPlYtNXqrU85ympIs9vzAorybfFW2iZ5bjkUPM8R3XhYd35NpSytJhQ+23LQwjGE+IQolz7xPnCUrG1rLxUaYPwfhDJcDJ/0yuq3kBId5MxOQxRUqzbh+dcZSCGMGsLrBb23cdpDX8DqGpn6w9DQ335BLi/x3/e99YszaNT55Ho8sb/Joyb5+QveeF6cDo9SXA28BTzjc0XUeLK9BFIxk="
  on:
    branch: master
