language: node_js
node_js:
- lts/*
before_script: npm run build
after_success: npm run coverage
deploy:
  skip_cleanup: true
  provider: npm
  repo: warerebel/azureblobstoragehelper
  email: npm@warerebel.com
  api_key:
    secure: "R9ruc/7JbOteDrC5xP/iVaIsnfs0APaVT0TCvgDCdbkYliTYFRb8xMNZmYJOTUrY01WT9JTn5EGBCbenMTCVvYSbLp1odoPjSfSscR3480eicdk0aS24KUoZCvo2H9Lz1oK+NPfx9IpP9vdGU4HxuslRVLoWqDnM/8eb12zmWC2BOUqCa6IiExd6Ek5/sXqzLO6S8J4kPUhZfHKZcuC9wFI2YGlRDrD4e35z59/bGDY9ZU7Ip0wtCvAnnHLY596W1W1CF7H7MHfR9Hmtv2ysV6BnxH1jYk3b5UM6LCtIJz4l+GMXTnMvxer+jq7gOAJNaLL+Wjosg2tVWFxaCnBy6fBJdJFttGJc6QuiwbBBwojwbHaEErzjmVvZFmpdPG66UVfx0K+uaqPk9xkwDA3dPXe3GfX2YZtD+D91T/FB/6aUQsi8IWZTswl5ZueMsDHVFleN9IRf7GMd/oV1ClXWTgnully/lSz7yEDwBYcXIVQjLCcRNSQVvKiYz6VOtvlIRcG351/KLSv3U0cJPsNTA48qH52xre/hQRVTRlmy5330/+20HB6X+U9AIMhLwzmXFYZadDdM/uGsz+m7cjtPfb1le54RgQQDvhU6PGqWB0F/MyisYoAVPDmQZM/nGDo5JAmw6YAbZaMORFvwd5U+v96KJizqoWuKqrzVDf6Fb5U="
  on:
    branch: master
